---
- name: Get PMON processes
  hosts: "{{ target_hosts }}"
  gather_facts: no

  tasks:
    - name: List PMON processes
      shell: ps -ef | grep pmon | grep -v grep | cat
      register: pmon_output

    - name: Show PMON process list
      debug:
        var: pmon_output.stdout_lines