name: CSR Preprod schema Refresh from Prod 

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      prod_csr_account_name: 
        description: CSR production account name
        required: true
        type: choice
        options: 
          - "corporate-staff-rostering-production"

      prod_csr_hostname: 
        description: CSR production hostname
        required: true
        type: choice
        options: 
          - "pd-csr-db-a"

      preprod_csr_account_name: 
        description: CSR preproduction account name
        required: true
        type: choice
        options: 
          - "corporate-staff-rostering-preproduction"

      preprod_csr_hostname: 
        description: CSR preproduction hostname
        required: true
        type: choice
        options: 
          - "pp-csr-db-a"

      step_action:
        description: Actions to do
        required: true
        type: choice
        options: 
          - prod-schema-export
          - preprod-schema-import
          # - both

      dump_file_string:
        description: 'Datapump file string for identification'
        required: true
        type: string

jobs:

  run_prod_export_ansible:
    name: Run ansible against CSR production 
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.step_action  == 'prod-schema-export' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4
        with:
          ref: ${{ github.ref }}

      - name: Get Account Details
        uses: ./.github/actions/get_account_details
        id: account
        with:
          account_name: ${{ inputs.prod_csr_account_name }}
          secrets_json: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENT_MANAGEMENT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: "${{ steps.account.outputs.role_arn }}"
          role-session-name: "${{ steps.account.outputs.role_session_name }}"
          aws-region: eu-west-2
      - name: Checkout MP Configuration Management Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: ministryofjustice/modernisation-platform-configuration-management
          token: ${{ secrets.DSO_GITHUB_PAT }}
          ref: main
          path: configuration-management
          fetch-depth: 1
      - name: Setup Ansible
        run: |
          DEPENDENCIES=`cat requirements.txt | tr '\n' ' '`
          pipx inject ansible-core $DEPENDENCIES
          ansible-galaxy role install -r requirements.yml
          ansible-galaxy collection install -r requirements.yml
        working-directory: configuration-management/ansible
      - name: Check Ansible Inventory
        run: |
          echo "Checking ansible-inventory --graph"
          ansible-inventory --graph > /dev/null
          echo "Checking ansible-inventory --host ${{ inputs.prod_csr_hostname }}"
          ansible-inventory --host ${{ inputs.prod_csr_hostname }} > /dev/null
        working-directory: configuration-management/ansible
      - name: Run Ansible Ping
        run: |
          ansible -m ping ${{ inputs.prod_csr_hostname }}
        working-directory: configuration-management/ansible
      - name: Run Ansible Playbook against Production CSR to take export of schemas
        run: |
          ansible-playbook site.yml -e force_role=csr-preprod-refresh --tags csr_adhoc_schema_export_prod --limit ${{ inputs.prod_csr_hostname }} --extra-vars "EXPDP_TAG=${{ inputs.dump_file_string }}"
        working-directory: configuration-management/ansible

  run_preprod_import_ansible:
    name: Run ansible against target database EC2
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.step_action  == 'preprod-schema-import' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4
        with:
          ref: ${{ github.ref }}

      - name: Get Account Details
        uses: ./.github/actions/get_account_details
        id: account
        with:
          account_name: ${{ inputs.preprod_csr_account_name }}
          secrets_json: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENT_MANAGEMENT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
        with:
          role-to-assume: "${{ steps.account.outputs.role_arn }}"
          role-session-name: "${{ steps.account.outputs.role_session_name }}"
          aws-region: eu-west-2
      - name: Checkout MP Configuration Management Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: ministryofjustice/modernisation-platform-configuration-management
          token: ${{ secrets.DSO_GITHUB_PAT }}
          ref: main
          path: configuration-management
          fetch-depth: 1
      - name: Setup Ansible
        run: |
          DEPENDENCIES=`cat requirements.txt | tr '\n' ' '`
          pipx inject ansible-core $DEPENDENCIES
          ansible-galaxy role install -r requirements.yml
          ansible-galaxy collection install -r requirements.yml
        working-directory: configuration-management/ansible
      - name: Check Ansible Inventory
        run: |
          echo "Checking ansible-inventory --graph"
          ansible-inventory --graph > /dev/null
          echo "Checking ansible-inventory --host ${{ inputs.preprod_csr_hostname }}"
          ansible-inventory --host ${{ inputs.preprod_csr_hostname }} > /dev/null
        working-directory: configuration-management/ansible
      - name: Run Ansible Ping
        run: |
          ansible -m ping ${{ inputs.preprod_csr_hostname }}
        working-directory: configuration-management/ansible
      - name: Run Ansible Playbook against preproduction CSR to do import of schemas using production dumpfiles 
        run: |
          ansible-playbook site.yml -e force_role=csr-preprod-refresh --tags csr_adhoc_schema_import_from_prod --limit ${{ inputs.preprod_csr_hostname }} --extra-vars "EXPDP_TAG=${{ inputs.dump_file_string }}"
        working-directory: configuration-management/ansible
