---
name: JumpServer Stop

on:
  workflow_dispatch:
    inputs:
      jumpserver:
        type: choice
        description: Which environment to stop
        default: test
        options:
          - development
          - test
          - preproduction
          - production
      dryrun:
        type: choice
        description: Dryrun mode (leave as false unless testing)
        default: false
        options:
          - true
          - false

  schedule:
    # runs at 22:05 local time.
    - cron: "05 22 * * 1-5"
      timezone: "Europe/London"    

permissions:
  id-token: write
  contents: read

run-name: "JumpServer Stop (${{ inputs.jumpserver }}${{ inputs.dryrun == 'true' && ' dryrun)' || ')' }}"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      gha_environment: "${{ steps.parseinput.outputs.gha_environment }}"
      matrix: "${{ steps.parseinput.outputs.matrix }}"
      jumpservers: "${{ steps.parseinput.outputs.jumpservers }}"
      script_flags: "${{ steps.parseinput.outputs.script_flags }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          ref: ${{ github.ref }}

      - name: Parse Workflow Inputs
        id: parseinput
        run: |
          get_strategy_matrix() {
            echo '{"include":['
            (
              for jumpserver in $@; do
                echo '{"jumpserver": "'$jumpserver'"},'
              done
            ) | sed '$s/,$//'
            echo ']}'
          }
          gha_environment="hmpps-domain-services"
          jumpservers=
          script_flags=
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            jumpservers="${{ github.event.inputs.jumpserver }}"
            if [[ "${{ github.event.inputs.dryrun }}" == "true" ]]; then
              script_flags="$script_flags -d"
              gha_environment="hmpps-domain-services-dryrun"
            fi
          elif [[ "${GITHUB_EVENT_NAME}" == "schedule" ]]; then
            gha_environment="hmpps-domain-services-schedule"
            jumpservers="development test"
          else
            echo "Unsupported event ${GITHUB_EVENT_NAME}"
            exit 1
          fi
          echo "jumpservers=${jumpservers} gha_environment=${gha_environment} script_flags=${script_flags}"
          echo "gha_environment=${gha_environment}" >> $GITHUB_OUTPUT
          echo "matrix=$(get_strategy_matrix $jumpservers | jq -c)" >> $GITHUB_OUTPUT
          echo "jumpservers=${jumpservers}" >> $GITHUB_OUTPUT
          echo "script_flags=${script_flags}" >> $GITHUB_OUTPUT

  stop:
    environment: "${{ needs.setup.outputs.gha_environment }}-${{ matrix.jumpserver }}"
    name: Stop
    needs: setup
    if: ${{ needs.setup.outputs.jumpservers != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          ref: ${{ github.ref }}

      - name: Get Account Name
        env:
          jumpserver: "${{ matrix.jumpserver }}"
        id: account_name
        run: |
          account_name=$(src/jumpserver/jumpserver_control.sh -z "$jumpserver")
          echo "account_name=${account_name}"
          echo "account_name=${account_name}" >> $GITHUB_OUTPUT

      - name: Get Account Id
        uses: ./.github/actions/get_account_details
        id: account
        with:
          account_name: ${{ steps.account_name.outputs.account_name }}
          secrets_json: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENT_MANAGEMENT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885  # v6.1.1
        with:
          role-to-assume: "${{ steps.account.outputs.role_arn }}"
          role-session-name: "${{ steps.account.outputs.role_session_name }}"
          aws-region: eu-west-2

      - name: Get Current State
        id: current_state
        env:
          jumpserver: "${{ matrix.jumpserver }}"
          script_flags: "${{ needs.setup.outputs.script_flags }}"
        run: |
          ec2_state=$(src/jumpserver/jumpserver_control.sh $script_flags -p display "$jumpserver")
          echo "$ec2_state"
          maintenance_mode=$(src/jumpserver/jumpserver_control.sh $script_flags -m "$jumpserver")
          not_stopped_count=$(echo "$ec2_state" | grep -v terminated | grep -v stopped | wc -l)
          echo "not_stopped_count=${not_stopped_count} maintenance_mode=${maintenance_mode}"
          echo "not_stopped_count=${not_stopped_count}" >> $GITHUB_OUTPUT
          echo "maintenance_mode=${maintenance_mode}" >> $GITHUB_OUTPUT

      - name: Enable Maintenance Mode
        env:
          jumpserver: "${{ matrix.jumpserver }}"
          script_flags: "${{ needs.setup.outputs.script_flags }}"
        if: steps.current_state.outputs.maintenance_mode == 'disabled'
        run: |
          src/jumpserver/jumpserver_control.sh -1 $script_flags "$jumpserver"

      - name: Set Instance State
        env:
          jumpserver: "${{ matrix.jumpserver }}"
          script_flags: "${{ needs.setup.outputs.script_flags }}"
        if: steps.current_state.outputs.not_stopped_count != '0'
        run: |
          src/jumpserver/jumpserver_control.sh $script_flags -p off "$jumpserver"
