---
name: NCR Environment Stop

on:
  workflow_dispatch:
    inputs:
      ncr_environment:
        type: choice
        description: Which nomis combined reporting environment to stop
        default: t1
        options:
          - t1
          - pp
          - pd
      stop_or_shutdown:
        type: choice
        description: Choose stop to leave the EC2s running, or shutdown to powerdown EC2s
        default: shutdown
        options:
          - stop
          - shutdown
      pipeline_stages:
        type: string
        description: Limit which stages of the stop process to run, 0-8 or all
        default: all
      pipeline_stage3_wait_secs:
        type: number
        description: How many seconds to wait in stage 3 after disabling of services
        default: 600
      dryrun:
        type: choice
        description: Dryrun mode (leave as false unless testing)
        default: false
        options:
          - true
          - false
      verbose:
        type: choice
        description: Enable verbose output
        default: false
        options:
          - true
          - false

  schedule:
    # runs at 7pm local time. 2 entries to deal with BST/GMT
    - cron: "05 18 * * 1-5"
    - cron: "05 19 * * 1-5"

permissions:
  id-token: write
  contents: read

run-name: "NCR Environent Stop (${{ inputs.ncr_environment }}${{ inputs.dryrun == 'true' && ' dryrun)' || ')' }}"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      matrix: "${{ steps.parseinput.outputs.matrix }}"
      ncr_environments: "${{ steps.parseinput.outputs.ncr_environments }}"
      review_needed: "{{ steps.parseinput.outputs.review_needed }}"
      script_flags: "${{ steps.parseinput.outputs.script_flags }}"
      pipeline_stages: "${{ steps.parseinput.outputs.pipeline_stages }}"
      stop_or_shutdown: "${{ steps.parseinput.outputs.stop_or_shutdown }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
        with:
          ref: ${{ github.ref }}

      - name: Parse Workflow Inputs
        id: parseinput
        run: |
          get_strategy_matrix() {
            echo '{"include":['
            (
              for ncr_environment in $@; do
                echo '{"ncr_environment": "'$ncr_environment'"},'
              done
            ) | sed '$s/,$//'
            echo ']}'
          }
          ncr_environments=
          review_needed="true"
          script_flags=
          pipeline_stages=all
          stop_or_shutdown=shutdown
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            pipeline_stages="${{ github.event.inputs.pipeline_stages }}"
            ncr_environments="${{ github.event.inputs.ncr_environment }}"
            stop_or_shutdown="${{ github.event.inputs.stop_or_shutdown }}"
            script_flags="$script_flags -3 ${{ github.event.inputs.pipeline_stage3_wait_secs }}"
            if [[ "${{ github.event.inputs.dryrun }}" == "true" ]]; then
              script_flags="$script_flags -d"
              review_needed="false"
            fi
            if [[ "${{ github.event.inputs.verbose }}" == "true" ]]; then
              script_flags="$script_flags -v"
            fi
          elif [[ "${GITHUB_EVENT_NAME}" == "schedule" ]]; then
            cron_time="${{ github.event.schedule }}"
            is_bst=1
            review_needed="false"
            if [[ $(TZ=Europe/London date +%H) == $(date -u +%H) ]]; then
              is_bst=0
            fi
            if [[ "${cron_time}" == '05 18 * * 1-5' ]]; then
              if ((is_bst == 1)); then
                ncr_environments="t1 pp" # space separated list
              fi
            elif [[ "${cron_time}" == '05 19 * * 1-5' ]]; then
              if ((is_bst == 0)); then
                ncr_environments="t1 pp" # space separated list
              fi
            else
              echo "Unsupported schedule cron ${cron_time}"
              exit 1
            fi
          else
            echo "Unsupported event ${GITHUB_EVENT_NAME}"
            exit 1
          fi
          echo "ncr_environments=${ncr_environments} review_needed=${review_needed} script_flags=${script_flags} pipeline_stages=${pipeline_stages} stop_or_shutdown=${stop_or_shutdown}"
          echo "matrix=$(get_strategy_matrix $ncr_environments | jq -c)" >> $GITHUB_OUTPUT
          echo "ncr_environments=${ncr_environments}" >> $GITHUB_OUTPUT
          echo "review_needed=${review_needed}" >> $GITHUB_OUTPUT
          echo "script_flags=${script_flags}" >> $GITHUB_OUTPUT
          echo "pipeline_stages=${pipeline_stages}" >> $GITHUB_OUTPUT
          echo "stop_or_shutdown=${stop_or_shutdown}" >> $GITHUB_OUTPUT

  stop:
    environment: "nomis-combined-reporting-${{ matrix.ncr_environment }}${{ !needs.setup.outputs.review_needed && '-no-review' }}"
    name: Stop
    needs: setup
    if: ${{ needs.setup.outputs.ncr_environments != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
        with:
          ref: ${{ github.ref }}

      - name: Get Account Name
        env:
          ncr_environment: "${{ matrix.ncr_environment }}"
        id: account_name
        run: |
          account_name=$(src/nomis-combined-reporting/ncr_control.sh -e "$ncr_environment" env aws-account)
          echo "account_name=${account_name}"
          echo "account_name=${account_name}" >> $GITHUB_OUTPUT

      - name: Get Account Id
        id: account_id
        run: |
          account_id="${{ fromJSON(secrets.MODERNISATION_PLATFORM_ENVIRONMENT_MANAGEMENT).account_ids[steps.account_name.outputs.account_name] }}"
          echo "account_id=${account_id}"
          echo "account_id=${account_id}" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502  # v4.0.2
        with:
          role-to-assume: "arn:aws:iam::${{ steps.account_id.outputs.account_id }}:role/modernisation-platform-oidc-cicd"
          role-session-name: "github-${{ github.repository_id }}-${{ github.run_id }}-${{ matrix.ncr_environment }}-1"
          aws-region: eu-west-2

      - name: Stop
        env:
          ncr_environment: "${{ matrix.ncr_environment }}"
          script_flags: "${{ needs.setup.outputs.script_flags }}"
          stop_or_shutdown: "${{ needs.setup.outputs.stop_or_shutdown }}"
          pipeline_stages: "${{ needs.setup.outputs.pipeline_stages }}"
        run: |
          src/nomis-combined-reporting/ncr_control.sh -e "$ncr_environment" $script_flags pipeline "$stop_or_shutdown" "$pipeline_stages"
