---
name: NOMIS Environment Start

on:
  workflow_dispatch:
    inputs:
      nomis_environment:
        type: choice
        description: Which nomis environment to start
        options:
          - t1
          - t2
          - t3
          - lsast
          - preprod
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      account_name: "{{ steps.parseinput.outputs.account_name }}"
      nomis_environment: "{{ steps.parseinput.outputs.nomis_environment }}"
      role_arn: "{{ steps.account.outputs.role_arn }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
        with:
          ref: ${{ github.ref }}

      - name: Parse Workflow Inputs
        id: parseinput
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            nomis_environment="${{ github.event.inputs.nomis_environment }}"
          elif [[ "${GITHUB_EVENT_NAME}" == "schedule" ]]; then
            nomis_environment="TODO"
          else
            echo "Unsupported event ${GITHUB_EVENT_NAME}"
            exit 1
          fi
          account_name=$(src/nomis/get_nomis_environment.sh -a "$nomis_environment")
          echo "account_name=${account_name} nomis_environment=${nomis_environment}"
          echo "account_name=${account_name}" >> $GITHUB_OUTPUT
          echo "nomis_environment=${nomis_environment}" >> $GITHUB_OUTPUT

      - name: Debug
        run: |
          echo "${{ env.MODERNISATION_PLATFORM_ENVIRONMENT_MANAGEMENT }}"

      - name: Get AWS Account Details
        id: account
        run: |
          echo "account name: ${{ steps.parseinput.outputs.account_name }}"

          account_id="${{ fromJSON(env.MODERNISATION_PLATFORM_ENVIRONMENT_MANAGEMENT).account_ids[steps.parseinput.outputs.account_name] }}"
          role_arn="arn:aws:iam::${account_id}:role/modernisation-platform-oidc-cicd"
          echo "role arn:     ${role_arn}"
          echo "role_arn=${role_arn}" >> $GITHUB_OUTPUT

  get_nomis_environment_status:
    name: Get Nomis Environment Status
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      asg_name: "{{ steps.active_asg_stats.outputs.asg_name }}"
      desired_count: "{{ steps.active_asg_stats.outputs.desired_count }}"
      healthy_instance_count: "{{ steps.active_asg_stats.outputs.healthy_instance_count }}"
      maintenance_mode: "{{ steps.active_asg_stats.outputs.maintenance_mode }}"
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502  # v4.0.2
        with:
          role-to-assume: "${{ needs.setup.outputs.role_arn }}"
          role-session-name: "github-${{ github.repository_id }}-${{ github.run_id }}-1"
          aws-region: eu-west-2

      - name: Checkout Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
        with:
          ref: ${{ github.ref }}

      - name: Get Active Weblogic ASG Stats
        id: active_asg_stats
        env:
          nomis_environment="${{ needs.setup.outputs.nomis_environment }}"
        run: |
          asg_name=$(src/nomis/get_nomis_environment.sh -t "$nomis_environment")
          desired_count=$(src/nomis/get_nomis_environment.sh -d "$nomis_environment")
          healthy_instance_count=$(src/nomis/get_nomis_environment.sh -h "$nomis_environment")
          maintenance_mode=$(src/nomis/get_nomis_environment.sh -m "$nomis_environment")
          echo "asg_name=${asg_name} desired_count=${desired_count} healthy_instance_count=${healthy_instance_count} maintenance_mode=${maintenance_mode}"
          echo "asg_name=${asg_name}" >> $GITHUB_OUTPUT
          echo "desired_count=${desired_count}" >> $GITHUB_OUTPUT
          echo "healthy_instance_count=${healthy_instance_count}" >> $GITHUB_OUTPUT
          echo "maintenance_mode=${maintenance_mode}" >> $GITHUB_OUTPUT

#  start_weblogic_instance:
#    name: Start Weblogic Instance
#    needs: get_nomis_environment_status
#    runs-on: ubuntu-latest
#    if: needs.get_nomis_environment_status.output.desired_count == '0'
#    steps:
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502  # v4.0.2
#        with:
#          role-to-assume: "${{ needs.setup.outputs.role_arn }}"
#          role-session-name: "github-${{ github.repository_id }}-${{ github.run_id }}-1"
#          aws-region: eu-west-2
#
#      - name: Set ASG Desired Count
#        env:
#          asg_name="${{ needs.get_nomis_environment_status.output.asg_name }}"
#        run: |
#          echo aws autoscaling set-desired-capacity --desired-capacity 1 --auto-scaling-group-name "$asg_name" >&2
#          # aws autoscaling set-desired-capacity --desired-capacity 1 --auto-scaling-group-name "$asg_name"
#
#  wait_for_healthy_instance:
#    name: Wait for healthy Weblogic Instance
#    needs: get_nomis_environment_status
#    runs-on: ubuntu-latest
#    if: needs.get_nomis_environment_status.output.healthy_instance_count == '0'
#    steps:
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502  # v4.0.2
#        with:
#          role-to-assume: "${{ needs.setup.outputs.role_arn }}"
#          role-session-name: "github-${{ github.repository_id }}-${{ github.run_id }}-1"
#          aws-region: eu-west-2
#
#      - name: Checkout Repository
#        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
#        with:
#          ref: ${{ github.ref }}
#
#      - name: Wait for healthy Weblogic Instance
#        run: |
#          sleep 5
#
#  disable_maintenance_mode:
#    name: Start Weblogic Instance
#    needs: wait_for_healthy_instance
#    runs-on: ubuntu-latest
#    if: needs.get_nomis_environment_status.output.maintenance_mode == 'enabled'
#    steps:
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502  # v4.0.2
#        with:
#          role-to-assume: "${{ needs.setup.outputs.role_arn }}"
#          role-session-name: "github-${{ github.repository_id }}-${{ github.run_id }}-1"
#          aws-region: eu-west-2
#
#      - name: Checkout Repository
#        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
#        with:
#          ref: ${{ github.ref }}
#
#      - name: Get Maintenance Mode Weblogic Status
#        id: asg_current_asg_desired_count
#        env:
#          nomis_environment="${{ steps.parseinput.outputs.nomis_environment }}"
#        run: |
#          nomis_environment="${{ steps.parseinput.outputs.nomis_environment }}"
#          asg="${{ steps.nomis_environment.outputs.asg }}"
#          echo "src/run_script_on_ec2.sh first ${asg} lb_maintenance_mode.sh '/home/oracle/admin/scripts/lb_maintenance_mode.sh check'"
#          src/run_script_on_ec2.sh first ${asg} lb_maintenance_mode.sh "/home/oracle/admin/scripts/lb_maintenance_mode.sh check"
