---
name: NCR Environment Start

on:
  workflow_dispatch:
    inputs:
      ncr_environment:
        type: choice
        description: Which nomis combined reporting environment to start
        default: t1
        options:
          - t1
          - preprod
      dryrun:
        type: choice
        description: Dryrun mode (leave as false unless testing)
        default: false
        options:
          - true
          - false

  schedule:
    # runs at 06:30 and 09:30 local time. 2 entries to deal with BST/GMT
    # - cron: "30 5 * * 1-5"
    # - cron: "30 6 * * 1-5"
    # - cron: "30 8 * * 1-5"
    # - cron: "30 9 * * 1-5"

permissions:
  id-token: write
  contents: read

run-name: "NCR Environent Start (${{ inputs.ncr_environment }}${{ inputs.dryrun == 'true' && ' dryrun)' || ')' }}"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      dryrun: "${{ steps.parseinput.outputs.dryrun }}"
      matrix: "${{ steps.parseinput.outputs.matrix }}"
      ncr_environments: "${{ steps.parseinput.outputs.ncr_environments }}"
      script_flags: "${{ steps.parseinput.outputs.script_flags }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
        with:
          ref: ${{ github.ref }}

      - name: Parse Workflow Inputs
        id: parseinput
        run: |
          get_strategy_matrix() {
            echo '{"include":['
            (
              for ncr_environment in $@; do
                echo '{"ncr_environment": "'$ncr_environment'"},'
              done
            ) | sed '$s/,$//'
            echo ']}'
          }
          ncr_environments=
          script_flags=
          dryrun=0
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            ncr_environments="${{ github.event.inputs.ncr_environment }}"
            if [[ "${{ github.event.inputs.dryrun }}" == "true" ]]; then
              script_flags="$script_flags -d"
              dryrun=1
            fi
          elif [[ "${GITHUB_EVENT_NAME}" == "schedule" ]]; then
            cron_time="${{ github.event.schedule }}"
            is_bst=1
            if [[ $(TZ=Europe/London date +%H) == $(date -u +%H) ]]; then
              is_bst=0
            fi
            if [[ "${cron_time}" == '30 5 * * 1-5' || "${cron_time}" == '30 8 * * 1-5' ]]; then
              if ((is_bst == 1)); then
                ncr_environments="t1" # space separated list                
              fi
            elif [[ "${cron_time}" == '30 6 * * 1-5' || "${cron_time}" == '30 9 * * 1-5' ]]; then
              if ((is_bst == 0)); then
                ncr_environments="t1" # space separated list
              fi
            else
              echo "Unsupported schedule cron ${cron_time}"
              exit 1
            fi
          else
            echo "Unsupported event ${GITHUB_EVENT_NAME}"
            exit 1
          fi
          echo "ncr_environments=${ncr_environments} script_flags=${script_flags} dryrun=${dryrun}"
          echo "dryrun=${dryrun}" >> $GITHUB_OUTPUT
          echo "matrix=$(get_strategy_matrix $ncr_environments | jq -c)" >> $GITHUB_OUTPUT
          echo "ncr_environments=${ncr_environments}" >> $GITHUB_OUTPUT
          echo "script_flags=${script_flags}" >> $GITHUB_OUTPUT

  start:
    name: Start
    needs: setup
    if: ${{ needs.setup.outputs.ncr_environments != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b  # v4.1.4
        with:
          ref: ${{ github.ref }}

      - name: Get Account Name
        env:
          ncr_environment: "${{ matrix.ncr_environment }}"
        id: account_name
        run: |
          account_name=$(src/nomis_combined_reporting/ncr_control.sh -e "$ncr_environment" env account)
          echo "account_name=${account_name}"
          echo "account_name=${account_name}" >> $GITHUB_OUTPUT

      - name: Get Account Id
        id: account_id
        run: |
          account_id="${{ fromJSON(secrets.MODERNISATION_PLATFORM_ENVIRONMENT_MANAGEMENT).account_ids[steps.account_name.outputs.account_name] }}"
          echo "account_id=${account_id}"
          echo "account_id=${account_id}" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502  # v4.0.2
        with:
          role-to-assume: "arn:aws:iam::${{ steps.account_id.outputs.account_id }}:role/modernisation-platform-oidc-cicd"
          role-session-name: "github-${{ github.repository_id }}-${{ github.run_id }}-${{ matrix.ncr_environment }}-1"
          aws-region: eu-west-2
