name: OASYS Database Refresh

# NOTE: MODERNISATION_PLATFORM_ENVIRONMENT_MANAGEMENT secret is
# exact copy of the modernisation-platform environment_management
# secret. You can retrieve via AWS CLI like this:
#   aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-west-2:{{ modernisation-platform account id }}:secret:environment_management --output text --query SecretString --profile oassys-development

on:
  workflow_dispatch:

jobs:
  refresh_db:
    uses: ministryofjustice/dso-modernisation-platform-automation/.github/workflows/database_refresh.yml@DSOS-2668/db-refresh-pipeline-improvements
    with:
      source_oem_account_name: "hmpps-oem-production"
      source_oem_hostname: "prod-oem-a"
      source_db_name: "PROASYS"
      target_db_account_name: "oasys-preproduction"
      target_db_hostname: "pp-oasys-db-b"
      target_db_name: "PPROASYS"
    secrets:
      account_ids: ${{ fromJSON(secrets.MODERNISATION_PLATFORM_ENVIRONMENT_MANAGEMENT) }}
      dso_github_pat: ${{ secrets.DSO_GITHUB_PAT }}
