name: OASYS Database Refresh

# NOTE: MODERNISATION_PLATFORM_ENVIRONMENT_MANAGEMENT secret is
# exact copy of the modernisation-platform environment_management
# secret. You can retrieve via AWS CLI like this:
#   aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-west-2:{{ modernisation-platform account id }}:secret:environment_management --output text --query SecretString --profile oassys-development

on:
  workflow_dispatch:
    inputs:
      source_db_name:
        description: 'Source database name'
        required: true
        type: string
      target_db_hostname:
        description: 'Target database hostname or ansible group'
        required: true
        type: string
      target_db_name:
        description: 'Target database name'
        required: true
        type: string

jobs:
  refresh_db:
    uses: ministryofjustice/dso-modernisation-platform-automation/.github/workflows/database_refresh.yml@oasys_db_refresh_test
    with:
      source_oem_account_name: "hmpps-oem-production"
      source_oem_hostname: "prod-oem-a"
      source_db_name: "PROASYS"
      target_db_account_name: "oasys-preproduction"
      target_db_hostname: "pp-oasys-db-b"
      target_db_name: "PPROASYS"
    secrets:
      environment_management: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENT_MANAGEMENT }}
      dso_github_pat: ${{ secrets.DSO_GITHUB_PAT }}
